# Generated by Django 5.1.6 on 2025-02-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=50)),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('soil_quality', models.FloatField()),
                ('market_rate', models.FloatField()),
            ],
        ),
    ]
